version: 2

group_defaults:
  approve_by_comment:
    enabled: true
    approve_regex: '^!!\/approve'
  reset_on_push:
    enabled: true

groups:
  code-admins:
    required: 1
    users:
      - angussidney
      - Aralun  # Kyll
      - ArtOfCode-
      - AWegnerGitHub
      - doppeldeveloper  # doppelgreener
      - ferrybig
      - Fortunate-MAN  # Ashish Ahuja
      - Glorfindel83
      - hichris1234
      - honnza  # Jan Dvorak
      - magisch
      - Manishearth
      - metasmoke
      - NobodyNada
      - ProgramFOX
      - superplane39  # Mithrandir
      - surajrao
      - teward
      - tripleee
      - Undo1
    author_approval:
      ignored: true
    reject_value: -1
